name: lint.yml
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: LacunaRecipes

      - name: Run linter (dotnet format)
        run: dotnet format --verify-no-changes
        working-directory: LacunaRecipes
