name: tags.yml
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: UseDotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: 'Restore dependencies'
      run: dotnet restore
      working-directory: LacunaRecipes
    
    - name: 'Build solution'
      run: dotnet publish --configuration Release

      working-directory: LacunaRecipes

    - name: 'Archive files'
      run: tar -czf publish.rar LacunaRecipes/bin/Release/net9.0/publish/
      working-directory: LacunaRecipes

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'actionsLacunaRecipes'
        package: 'publish.rar'
      
        
      